services:
  catalog_db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U catalog -d catalog_db']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
      - ./infra/docker/postgres/init-test-database.sql:/docker-entrypoint-initdb.d/init-test-database.sql:ro

volumes:
  catalog_db_data:
